[profile.default]
src = "contracts"
out = "out"
libs = ["../lib"]
remappings = [
    "@openzeppelin/contracts/=../lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
baseSepolia = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
